package ecobill.module.base.ui.article;

import ecobill.module.base.ui.component.VerticalButton;
import ecobill.module.base.service.BaseService;
import ecobill.module.base.domain.Article;
import ecobill.module.base.domain.SystemUnit;
import ecobill.module.base.domain.SystemLocale;
import ecobill.module.base.domain.ArticleDescription;
import ecobill.module.base.dao.exception.NoSuchArticleException;
import ecobill.module.base.jasper.JasperViewer;
import ecobill.core.system.WorkArea;
import ecobill.core.system.Constants;
import ecobill.core.system.Internationalization;
import ecobill.util.exception.LocalizerException;
import ecobill.util.LocalizerUtils;

import javax.swing.*;

import org.springframework.beans.factory.InitializingBean;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Locale;

/**
 * ArticleUIOld.
 * <p/>
 * User: rro
 * Date: 15.07.2005
 * Time: 17:49:23
 *
 * @author Roman R&auml;dle
 * @version $Id: ArticleUI.java,v 1.3 2005/09/30 09:06:01 raedler Exp $
 * @since EcoBill 1.0
 */
public class ArticleUI extends JPanel implements InitializingBean, Internationalization {

    /**
     * In diesem <code>Log</code> können Fehler, Info oder sonstige Ausgaben erfolgen.
     * Diese Ausgaben können in einem separaten File spezifiziert werden.
     */
    private static final Log LOG = LogFactory.getLog(ArticleUI.class);

    private BaseService baseService;

    private ArticleTable articleTableOverview;
    private Description descriptionLabelling = new Description();
    private Description descriptionOverview = new Description();
    private DescriptionTable descriptionTableLabelling;
    private DescriptionTable descriptionTableOverview;
    private InputBundle inputBundleOverview;
    private InputDescription inputDescriptionLabelling;
    private Input inputOverview;
    private JPanel labelling = new JPanel();
    private JPanel overview = new JPanel();
    private JTabbedPane tabbedPane = new JTabbedPane();
    private VerticalButton verticalButtonLabelling = new VerticalButton();
    private VerticalButton verticalButtonOverview = new VerticalButton();

    private Long actualArticleId;

    public void afterPropertiesSet() throws Exception {
        initComponents();
        initLayout();

        tabbedPane.setEnabledAt(1, false);
    }

    public BaseService getBaseService() {
        return baseService;
    }

    public void setBaseService(BaseService baseService) {
        this.baseService = baseService;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        articleTableOverview = new ArticleTable(this, baseService);
        inputOverview = new Input(baseService);
        inputBundleOverview = new InputBundle(baseService);
        inputDescriptionLabelling = new InputDescription(baseService);
        descriptionTableOverview = new DescriptionTable(this, baseService);
        descriptionTableLabelling = new DescriptionTable(this, baseService);

        verticalButtonOverview.getSubmit().addActionListener(new ActionListener() {

            /**
             * @see ActionListener#actionPerformed(java.awt.event.ActionEvent)
             */
            public void actionPerformed(ActionEvent e) {
                saveOrUpdateArticle();
                articleTableOverview.renewArticleTableModel();
            }
        });

        verticalButtonOverview.getFirst().setEnabled(false);
        verticalButtonOverview.getBack().setEnabled(false);
        verticalButtonOverview.getNext().setEnabled(false);
        verticalButtonOverview.getLast().setEnabled(false);
        verticalButtonOverview.getCancel().setEnabled(false);

        verticalButtonOverview.getChange().addActionListener(new ActionListener() {

            /**
             * @see ActionListener#actionPerformed(java.awt.event.ActionEvent)
             */
            public void actionPerformed(ActionEvent e) {
                actualArticleId = null;

                resetInput();
            }
        });

        verticalButtonLabelling.getSubmit().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                saveOrUpdateArticleDescription();
            }
        });

        setLayout(new BorderLayout());
    }

    private void initLayout() {

        GroupLayout overviewLayout = new GroupLayout(overview);

        overview.setLayout(overviewLayout);

        overviewLayout.setHorizontalGroup(
                overviewLayout.createParallelGroup(GroupLayout.LEADING)
                        .add(GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(overviewLayout.createParallelGroup(GroupLayout.LEADING)
                                .add(articleTableOverview, GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                                .add(GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                                .add(verticalButtonOverview, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(overviewLayout.createParallelGroup(GroupLayout.LEADING, false)
                                        .add(GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                                                .add(inputOverview, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.RELATED)
                                                .add(inputBundleOverview, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .add(descriptionOverview, 0, 0, Short.MAX_VALUE))
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(descriptionTableOverview, GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                        .addContainerGap())
        );
        overviewLayout.setVerticalGroup(
                overviewLayout.createParallelGroup(GroupLayout.LEADING)
                        .add(GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(overviewLayout.createParallelGroup(GroupLayout.TRAILING, false)
                                .add(GroupLayout.LEADING, descriptionTableOverview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(verticalButtonOverview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(GroupLayout.LEADING, overviewLayout.createSequentialGroup()
                                .add(overviewLayout.createParallelGroup(GroupLayout.TRAILING, false)
                                        .add(GroupLayout.LEADING, inputBundleOverview, 0, 0, Short.MAX_VALUE)
                                        .add(inputOverview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(descriptionOverview, 0, 166, Short.MAX_VALUE)))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(articleTableOverview, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        tabbedPane.addTab(WorkArea.getMessage(Constants.OVERVIEW), overview);

        GroupLayout labellingLayout = new GroupLayout(labelling);
        labelling.setLayout(labellingLayout);
        labellingLayout.setHorizontalGroup(
                labellingLayout.createParallelGroup(GroupLayout.LEADING)
                        .add(GroupLayout.LEADING, labellingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(labellingLayout.createParallelGroup(GroupLayout.LEADING)
                                .add(descriptionTableLabelling, GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                                .add(GroupLayout.LEADING, labellingLayout.createSequentialGroup()
                                .add(verticalButtonLabelling, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(inputDescriptionLabelling, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.RELATED)
                                .add(descriptionLabelling, GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)))
                        .addContainerGap())
        );
        labellingLayout.setVerticalGroup(
                labellingLayout.createParallelGroup(GroupLayout.LEADING)
                        .add(GroupLayout.LEADING, labellingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(labellingLayout.createParallelGroup(GroupLayout.TRAILING, false)
                                .add(GroupLayout.LEADING, descriptionLabelling, 0, 0, Short.MAX_VALUE)
                                .add(GroupLayout.LEADING, inputDescriptionLabelling, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(verticalButtonLabelling, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(descriptionTableLabelling, GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addContainerGap())
        );
        tabbedPane.addTab(WorkArea.getMessage(Constants.LABELLING), labelling);

        add(tabbedPane, BorderLayout.CENTER);
    }

    public ArticleTable getArticleTable() {
        return articleTableOverview;
    }

    public DescriptionTable getDescriptionTable() {
        return descriptionTableOverview;
    }

    /**
     * @see ecobill.core.system.Internationalization#reinitI18N()
     */
    public void reinitI18N() {
        tabbedPane.setTitleAt(0, WorkArea.getMessage(Constants.OVERVIEW));
        tabbedPane.setTitleAt(1, WorkArea.getMessage(Constants.LABELLING));

        articleTableOverview.reinitI18N();
        descriptionLabelling.reinitI18N();
        descriptionOverview.reinitI18N();
        descriptionTableLabelling.reinitI18N();
        descriptionTableOverview.reinitI18N();
        inputBundleOverview.reinitI18N();
        inputDescriptionLabelling.reinitI18N();
        inputOverview.reinitI18N();
    }

    private void resetInput() {

        tabbedPane.setEnabledAt(1, false);

        inputOverview.setArticleNumber("");
        inputOverview.setPrice(0D);
        inputOverview.setInStock(0D);
        inputBundleOverview.setCapacity(0D);
        descriptionOverview.setDescription("");
    }

    public void showArticle(Long id) {

        tabbedPane.setEnabledAt(1, true);

        actualArticleId = id;

        Article article = (Article) baseService.load(Article.class, id);

        descriptionTableOverview.renewTableModel(article);
        
        inputOverview.setArticleNumber(article.getArticleNumber());
        inputOverview.setUnit(article.getSystemUnit());
        inputOverview.setPrice(article.getPrice());
        inputOverview.setInStock(article.getInStock());
        inputBundleOverview.setUnit(article.getBundleSystemUnit());
        inputBundleOverview.setCapacity(article.getBundleCapacity());
        descriptionOverview.setDescription(article.getLocalizedDescription());
    }

    /**
     * Speichert oder ändert den Artikel mit den in der UI angegebenen Daten.
     */
    private void saveOrUpdateArticle() {

        tabbedPane.setEnabledAt(1, true);

        Article article = null;
        if (actualArticleId != null) {
            article = (Article) baseService.load(Article.class, actualArticleId);
        }

        if (article == null) {
            article = new Article();
        }

        article.setArticleNumber(inputOverview.getArticleNumber());
        article.setSystemUnit(inputOverview.getUnit());
        article.setPrice(inputOverview.getPrice());
        article.setInStock(inputOverview.getInStock());
        article.setBundleSystemUnit(inputBundleOverview.getUnit());
        article.setBundleCapacity(inputBundleOverview.getCapacity());

        SystemLocale systemLocale = baseService.getSystemLocaleByLocale(WorkArea.getLocale());

        ArticleDescription articleDescription;
        try {
            articleDescription = article.getLocalizedArticleDescription();
        }
        catch (LocalizerException le) {
            if (LOG.isDebugEnabled()) {
                LOG.debug(le.getMessage());
            }
            articleDescription = new ArticleDescription();
        }

        articleDescription.setDescription(descriptionOverview.getDescription());
        articleDescription.setSystemLocale(systemLocale);

        article.addArticleDescription(articleDescription);

        baseService.saveOrUpdate(article);
    }

    private void saveOrUpdateArticleDescription() {

        Article article = null;
        if (actualArticleId != null) {
            article = (Article) baseService.load(Article.class, actualArticleId);
        }

        Locale locale = inputDescriptionLabelling.getPreparedLocale();

        SystemLocale systemLocale = baseService.getSystemLocaleByLocale(locale);

        ArticleDescription articleDescription;
        try {
            articleDescription = (ArticleDescription) LocalizerUtils.getExactLocalizedObject(article.getDescriptions(), locale);
        }
        catch (LocalizerException le) {
            if (LOG.isDebugEnabled()) {
                LOG.debug(le.getMessage());
            }
            articleDescription = new ArticleDescription();
        }

        articleDescription.setDescription(descriptionLabelling.getDescription());
        articleDescription.setSystemLocale(systemLocale);

        article.addArticleDescription(articleDescription);

        baseService.saveOrUpdate(article);
    }

    public Long getActualArticleId() {
        return actualArticleId;
    }

    public void setActualArticleId(Long actualArticleId) {
        this.actualArticleId = actualArticleId;
    }
}
