/*
 * InputContact.java
 *
 * Created on 2. Oktober 2005, 01:03
 */

package ecobill.module.base.ui.businesspartner;

import ecobill.core.system.WorkArea;
import ecobill.core.system.Constants;

import javax.swing.*;

/**
 *
 * @author  Roman Georg Rädle
 */
public class InputContact extends javax.swing.JPanel {

    /** Creates new form InputContact */
    public InputContact() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        phoneL = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        faxL = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        emailL = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Kontakt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));

        phone.setMinimumSize(new java.awt.Dimension(120, 20));
        phone.setPreferredSize(new java.awt.Dimension(120, 20));


        fax.setMinimumSize(new java.awt.Dimension(120, 20));
        fax.setPreferredSize(new java.awt.Dimension(120, 20));


        email.setMinimumSize(new java.awt.Dimension(120, 20));
        email.setPreferredSize(new java.awt.Dimension(120, 20));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(phoneL)
                    .add(phone, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .add(faxL)
                    .add(fax, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .add(emailL)
                    .add(email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(phoneL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(phone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(faxL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reinitI18N();
    }
    // </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailL;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel faxL;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneL;
    // End of variables declaration


    public String getEmail() {
        return email.getText();
    }

    public void setEmail(String email) {
        this.email.setText(email);
    }

    public String getFax() {
        return fax.getText();
    }

    public void setFax(String fax) {
        this.fax.setText(fax);
    }

    public String getPhone() {
        return phone.getText();
    }

    public void setPhone(String phone) {
        this.phone.setText(phone);
    }

       public void reinitI18N() {

        emailL.setText(WorkArea.getMessage(Constants.EMAIL));
        faxL.setText(WorkArea.getMessage(Constants.FAX));
        phoneL.setText(WorkArea.getMessage(Constants.PHONE));
    }
}
