package ecobill.module.base.ui.help;

import javax.swing.*;
import java.awt.*;

// @todo document me!

/**
 * HelpUI.
 * <p/>
 * User: Paul Chef
 * Date: 21.10.2005
 * Time: 16:16:40
 *
 * @author Andreas Weiler
 * @version $Id: HelpUI.java,v 1.6 2005/10/22 14:39:46 jfuckerweiler Exp $
 * @since EcoBill 1.0
 */
public class HelpUI extends JFrame {

    /** Creates new form NewJFrame */
    public HelpUI() {

        initComponents();
        center();
    }

    public HelpBrowser helpBrowser = new HelpBrowser("/htmlfiles/help1.html");

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
          jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.add(helpBrowser);
        jTabbedPane1.setTitleAt(0, "Harry");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }
    // </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration

    private void center() {

        // Größe der eingestellten Bildschirmauflösung.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        double width = screenSize.getWidth();
        double height = screenSize.getHeight();

        // Größe des <code>JFrame</code>.
        Dimension frameSize = this.getSize();

        width -= frameSize.getWidth();
        height -= frameSize.getHeight();

        this.setLocation((int) width / 2, (int) height / 2);
    }

}

