package ecobill.module.base.ui.help;

import ecobill.core.system.WorkArea;
import ecobill.core.system.Constants;

import javax.swing.*;
import java.awt.*;

// @todo document me!

/**
 * HelpUI.
 * <p/>
 * User: Paul Chef
 * Date: 21.10.2005
 * Time: 16:16:40
 *
 * @author Andreas Weiler
 * @version $Id: HelpUI.java,v 1.9 2005/10/22 15:22:27 jfuckerweiler Exp $
 * @since EcoBill 1.0
 */
public class HelpUI extends JFrame {

    /** Creates new form NewJFrame */
    public HelpUI() {

        initComponents();
        reinitI18N();
        center();
    }

    public HelpBrowser helpBrowser1 = new HelpBrowser("./html/help/help1.html");
    public HelpBrowser helpBrowser2 = new HelpBrowser("./html/help/help2.html");
    public HelpBrowser helpBrowser3 = new HelpBrowser("./html/help/help3.html");
    public HelpBrowser helpBrowser4 = new HelpBrowser("./html/help/help4.html");
    public HelpBrowser helpBrowser5 = new HelpBrowser("./html/help/help5.html");

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
          helpTabbedPane = new javax.swing.JTabbedPane();

        helpTabbedPane.add(helpBrowser1);
        helpTabbedPane.add(helpBrowser2);
        helpTabbedPane.add(helpBrowser3);
        helpTabbedPane.add(helpBrowser4);
        helpTabbedPane.add(helpBrowser5);


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(helpTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(helpTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }
    // </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JTabbedPane helpTabbedPane;
    // End of variables declaration

    private void center() {

        // Größe der eingestellten Bildschirmauflösung.
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        double width = screenSize.getWidth();
        double height = screenSize.getHeight();

        // Größe des <code>JFrame</code>.
        Dimension frameSize = this.getSize();

        width -= frameSize.getWidth();
        height -= frameSize.getHeight();

        this.setLocation((int) width / 2, (int) height / 2);
    }

    public void reinitI18N() {
        helpTabbedPane.setTitleAt(0, WorkArea.getMessage(Constants.HELP_TABBED_PANE1));
        helpTabbedPane.setTitleAt(1, WorkArea.getMessage(Constants.HELP_TABBED_PANE2));
        helpTabbedPane.setTitleAt(2, WorkArea.getMessage(Constants.HELP_TABBED_PANE3));
        helpTabbedPane.setTitleAt(3, WorkArea.getMessage(Constants.HELP_TABBED_PANE4));
        helpTabbedPane.setTitleAt(4, WorkArea.getMessage(Constants.HELP_TABBED_PANE5));
    }

}

