/*
 * DeliveryOrderData.java
 *
 * Created on 6. Oktober 2005, 15:23
 */

package ecobill.module.base.ui.deliveryorder;

/**
 *
 * @author  Roman Georg Rädle
 */
public class DeliveryOrderData extends javax.swing.JPanel {

    /** Creates new form DeliveryOrderData */
    public DeliveryOrderData() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        deliveryOrderNumberL = new javax.swing.JLabel();
        deliveryOrderNumber = new javax.swing.JSpinner();
        deliveryOrderDateL = new javax.swing.JLabel();
        deliveryOrderDate = new javax.swing.JSpinner();
        typeL = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        prefixL = new javax.swing.JLabel();
        prefixScrollPane = new javax.swing.JScrollPane();
        prefix = new javax.swing.JTextArea();
        suffixL = new javax.swing.JLabel();
        suffixScrollPane = new javax.swing.JScrollPane();
        suffix = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Daten", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        deliveryOrderNumberL.setText("Lieferschein Nr.");

        deliveryOrderNumber.setMinimumSize(new java.awt.Dimension(80, 20));
        deliveryOrderNumber.setPreferredSize(new java.awt.Dimension(80, 20));

        deliveryOrderDateL.setText("Datum");

        deliveryOrderDate.setMinimumSize(new java.awt.Dimension(80, 20));
        deliveryOrderDate.setPreferredSize(new java.awt.Dimension(80, 20));

        typeL.setText("Art");

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        type.setMinimumSize(new java.awt.Dimension(120, 20));
        type.setPreferredSize(new java.awt.Dimension(120, 20));

        prefixL.setText("Prefix");

        prefix.setColumns(20);
        prefix.setRows(5);
        prefixScrollPane.setViewportView(prefix);

        suffixL.setText("Suffix");

        suffix.setColumns(20);
        suffix.setRows(5);
        suffixScrollPane.setViewportView(suffix);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(suffixScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(prefixScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(deliveryOrderNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(deliveryOrderNumberL))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(deliveryOrderDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(deliveryOrderDateL))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(typeL)
                                    .add(type, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .add(prefixL))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(suffixL)
                        .addContainerGap(274, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(deliveryOrderNumberL)
                        .add(deliveryOrderDateL))
                    .add(typeL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(deliveryOrderNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(deliveryOrderDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(type, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(prefixL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(prefixScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(suffixL)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(suffixScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }
    // </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JSpinner deliveryOrderDate;
    private javax.swing.JLabel deliveryOrderDateL;
    private javax.swing.JSpinner deliveryOrderNumber;
    private javax.swing.JLabel deliveryOrderNumberL;
    private javax.swing.JTextArea prefix;
    private javax.swing.JLabel prefixL;
    private javax.swing.JScrollPane prefixScrollPane;
    private javax.swing.JTextArea suffix;
    private javax.swing.JLabel suffixL;
    private javax.swing.JScrollPane suffixScrollPane;
    private javax.swing.JComboBox type;
    private javax.swing.JLabel typeL;
    // End of variables declaration

}
